'''
Stubs generated by PyStubbler version [1.0.8278.32530]
Date: Wednesday, 31 August 2022 18:04

Namespace: UserLibrary.Device.Measurements

In Assembly: TgcUserLibrary

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any
from UserLibrary.DataTypes import TimeCube, IntensityFrame, CubeRecord



class CubeFrameEventArgs:
#Class variables (static)
    Empty: Any

#Properties
    @property
    @TimeCube.setter
    def TimeCube(self) -> TimeCube: ...


#Class Methods


class IntensityFrameEventArgs:
#Class variables (static)
    Empty: Any

#Properties
    @property
    @Frame.setter
    def Frame(self) -> IntensityFrame: ...


#Class Methods


class TGCMeasurements:
#EventHandlers
    VideoCubeFrameHandler: Callable[[Any, CubeFrameEventArgs], None]    # void function(object sender, UserLibrary.Device.Measurements.CubeFrameEventArgs args) 
    CubeFrameGrabHandler: Callable[[Any, CubeFrameEventArgs], None]    # void function(object sender, UserLibrary.Device.Measurements.CubeFrameEventArgs args) 
    VideoIntensityFrameHandler: Callable[[Any, IntensityFrameEventArgs], None]    # void function(object sender, UserLibrary.Device.Measurements.IntensityFrameEventArgs args) 
    IntensityFrameGrabHandler: Callable[[Any, IntensityFrameEventArgs], None]    # void function(object sender, UserLibrary.Device.Measurements.IntensityFrameEventArgs args) 

#Properties
    @property
    @WindowOffset.setter
    def WindowOffset(self) -> int: ...

    @WindowOffset.setter
    def WindowOffset(self, value: int) -> None: ...

    @property
    @WindowWidth.setter
    def WindowWidth(self) -> int: ...

    @WindowWidth.setter
    def WindowWidth(self, value: int) -> None: ...

    @property
    @IntegrationCycles.setter
    def IntegrationCycles(self) -> int: ...

    @IntegrationCycles.setter
    def IntegrationCycles(self, value: int) -> None: ...

    @property
    @IntegrationMode.setter
    def IntegrationMode(self) -> int: ...

    @IntegrationMode.setter
    def IntegrationMode(self, value: int) -> None: ...

    @property
    @FramerateLimit.setter
    def FramerateLimit(self) -> int: ...

    @FramerateLimit.setter
    def FramerateLimit(self, value: int) -> None: ...

    @property
    @ImageRotation.setter
    def ImageRotation(self) -> int: ...

    @ImageRotation.setter
    def ImageRotation(self, value: int) -> None: ...


#Class Methods
    def GetCubeRecord(self) -> CubeRecord: ...

    def GrabCubeFrame(self) -> None: ...

    def GrabIntensityFrame(self) -> None: ...

    def MeasureCubeFrame(self) -> TimeCube: ...

    def MeasureIntensityFrame(self) -> IntensityFrame: ...

    @overload
    def SetCubeRecord(self, record: CubeRecord) -> None: ...

    @overload
    def SetCubeRecord(self, windowWidths: List[int], windowOffsets: List[int], windowCycles: List[int]) -> None: ...

    def StartCubeVideoStream(self) -> None: ...

    def StartIntensityVideoStream(self) -> None: ...

    def StopVideoStream(self) -> None: ...


