'''
Stubs generated by PyStubbler version [1.0.8278.32530]
Date: Wednesday, 31 August 2022 18:04

Namespace: UserLibrary.DataTypes

In Assembly: TgcUserLibrary

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any



class CallbackEventArgs:
#Class variables (static)
    Empty: Any

#Instance variables (non-static)
    ID: int
    Timestamp: Any
    Argument: int

#Constructors
    def __init__(self, id: int, timestamp: Any, argument: int): ...

#Class Methods


class CubeRecord:
#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, windowWidths: List[int], windowOffsets: List[int], windowCycles: List[int]): ...

#Properties
    @property
    @Length.setter
    def Length(self) -> int: ...

    @Length.setter
    def Length(self, value: int) -> None: ...

    @property
    @WindowWidths.setter
    def WindowWidths(self) -> List[int]: ...

    @WindowWidths.setter
    def WindowWidths(self, value: List[int]) -> None: ...

    @property
    @WindowOffsets.setter
    def WindowOffsets(self) -> List[int]: ...

    @WindowOffsets.setter
    def WindowOffsets(self, value: List[int]) -> None: ...

    @property
    @WindowCycles.setter
    def WindowCycles(self) -> List[int]: ...

    @WindowCycles.setter
    def WindowCycles(self, value: List[int]) -> None: ...


#Class Methods


class GpioEventArgs:
#Class variables (static)
    Empty: Any

#Instance variables (non-static)
    Channel: int
    Timestamp: Any
    State: int

#Class Methods


class IntensityFrame:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Width.setter
    def Width(self) -> int: ...

    @Width.setter
    def Width(self, value: int) -> None: ...

    @property
    @Cycles.setter
    def Cycles(self) -> int: ...

    @Cycles.setter
    def Cycles(self, value: int) -> None: ...

    @property
    @Offset.setter
    def Offset(self) -> int: ...

    @Offset.setter
    def Offset(self, value: int) -> None: ...

    @property
    @Resolution.setter
    def Resolution(self) -> Size: ...

    @Resolution.setter
    def Resolution(self, value: Size) -> None: ...

    @property
    @PixelData.setter
    def PixelData(self) -> List[float]: ...

    @PixelData.setter
    def PixelData(self, value: List[float]) -> None: ...


#Class Methods


class Size:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Width.setter
    def Width(self) -> int: ...

    @Width.setter
    def Width(self, value: int) -> None: ...

    @property
    @Height.setter
    def Height(self) -> int: ...

    @Height.setter
    def Height(self, value: int) -> None: ...


#Class Methods


class SubFrame(IntensityFrame):
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Index.setter
    def Index(self) -> int: ...

    @Index.setter
    def Index(self, value: int) -> None: ...


#Class Methods


class TimeCube:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Subframecount.setter
    def Subframecount(self) -> int: ...

    @property
    @Subframes.setter
    def Subframes(self) -> List[SubFrame]: ...

    @Subframes.setter
    def Subframes(self, value: List[SubFrame]) -> None: ...


#Class Methods

