'''
Stubs generated by PyStubbler version [1.0.8216.28667]
Date: Thursday, 30 June 2022 15:55

Namespace: PyStubblerTestAssembly.namespace2

In Assembly: PyStubblerTestAssembly

'''

from typing import Tuple, Set, Iterable, List
from typing import Dict, Callable, Any


class MyOtherClass:
#Instance variables (non-static)
    MyInt: int

#Constructors
    def __init__(self): ...

#Class Methods
