'''
Stubs generated by PyStubbler version [1.0.8287.20216]
Date: Friday, 09 September 2022 11:15

Namespace: PyStubblerTestAssembly.subnamespace

In Assembly: PyStubblerTestAssembly

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any



class MyOtherClass:
#Instance variables (non-static)
    MyInt: int

#Constructors
    def __init__(self): ...

#Class Methods

