'''
Stubs generated by PyStubbler version [1.0.8278.32530]
Date: Wednesday, 31 August 2022 18:04

Namespace: UserLibrary.Utils

In Assembly: TgcUserLibrary

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any



class ArrayReshapingUtils:
#Class Methods
    @staticmethod
    def ToJagged(mArray: List[Any]) -> List[List[Any]]: ...

    @staticmethod
    def ToMultiD(jArray: List[List[Any]]) -> List[Any]: ...

    @staticmethod
    def VectorToMatrix(jArray: List[Any], Dim1: int, Dim2: int) -> List[Any]: ...



class ArrayUtils:
#Class Methods
    @staticmethod
    def AreAllTheSameLength(arrays: List) -> bool: ...


